# -*- coding: utf-8 -*-
"""logparser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHLGmrfswsii1ZerwvqFWV2O-DFJsNE5
"""

with open("auth.log", "r") as f:
    for line in f:
        if "FAILED" in line:
            print(line.strip())



